### ISSUE TITLE
Refactoring Disqus plugin

### ISSUE THREAD

**Issue by nimitbhargava** [nimitbhargava/eip#1]
Current implementation of Disqus is pretty dirty. I found a good blog where it has mentioned a good way to implement Disqus. Blog URL - https://poanchen.github.io/blog/2017/07/27/how-to-add-disqus-to-your-jekyll-site

**Comment by omspacecode** [comment]
@nimitbhargava 
https://github.com/nimitbhargava/eip/pull/2/files
